### ISSUE TITLE
Images Dont Work

### ISSUE THREAD

**Issue by SgtD4rk** [Valokoodari/btd6-ahk#1]
Images are not associated with the script. i have it on a res folder and still doenst work

**Comment by Valokoodari** [comment]
Have you kept the original file structure?

It should be like this: 
```
btd6-ahk
├── dark_castle
│   └── easy-standard.ahk
└── res
    ├── gc_collect.png
    ├── ...
    └── gc_standard.png
```
Names of the folders 'btd6-ahk' and 'dark_castle' don't matter.


This should also work:
```
res
├── easy-standard.ahk
├── gc_collect.png
├── ...
└── gc_standard.png
```

But for example this will not work without changes:
```
btd6-ahk
├── easy-standard.ahk
└── res
    ├── gc_collect.png
    ├── ...
    └── gc_standard.png
```

**Comment by SgtD4rk** [comment]
Ye all god now ty. Just developed another problem
The images start clicking the egg and not the game. And everytime it clicks twice in the expert button it waits 2 sec and then xlick again causing jt to go to other game. I didnt modify nothing

**Comment by Valokoodari** [comment]
Which map does the script select when it selects the wrong map? And what egg?

Have you updated to the newest version of the script and other resources? (In older versions there was a problem with the map selection if the golden egg was on dark castle.)

**Comment by SgtD4rk** [comment]
Oh ok. Let me try

**Comment by SgtD4rk** [comment]
It works everything. Ty
