### ISSUE TITLE
dark dungeons issues with tower placement

### ISSUE THREAD

**Issue by autumn876** [Valokoodari/btd6-ahk#108]
title, for whatever reason snipers are not placed; making the script get stuck on this map during collection events. It looks like the round is somehow mistakenly offset by 10 rounds, as a 0-2-2 sniper would sometimes be deployed on round 40. nothing seems obviously wrong however

**Comment by autumn876** [comment]
UPDATE: FIXED

had to do some fuckery but I found out it was because the Tower::Upgrade fn clicked on the same spot the tower was placed, rather than pressing the escape key, leading to there being a visual offset in the round count. fixed by changing "Click(x,y)" to 
"Send("{vk1B}")" at the end of the upgrade function. 

Not closing issue quite yet but feel free to once it is patched

**Comment by Valokoodari** [comment]
Thank you. I wasn't able to replicate this issue on any of my machines but this should now be fixed by https://github.com/Valokoodari/btd6-ahk/commit/64b608425121879b5d0d96c4e500621ea817637b.
