### ISSUE TITLE
game difficulty always easy

### ISSUE THREAD

**Issue by zebruhfy** [Valokoodari/btd6-ahk#114]
I set the difficulty to hard but it goes through every difficulty and always plays easy. also after a game finishes it stops in the menu until there is user input then it finally selects another map. not sure if I'm doing something wrong but I have configured it as the directions show.

**Comment by zebruhfy** [comment]
I see in the updates "Easier difficulty will be chosen if the wanted difficulty is not available for current map" but hard mode is available on every map in the game. it even skips over medium mode.

**Comment by zebruhfy** [comment]
I fixed the part where it doesn't start another game after finishing and gets stuck in the menu after seeing a solution from an old thread. but im still having the issue where it only plays maps on easy mode. the only map it does on hard mode is dark castle.

**Comment by Valokoodari** [comment]
The script only has a strategy for easy for every map. Only Dark Castle and Logs currently have strategies for some of the other modes.
