### ISSUE TITLE
Map becomes stuck in the pause menu - (Dark castle - deflation) 

### ISSUE THREAD

**Issue by Hush-ti** [Valokoodari/btd6-ahk#115]
Not sure if the issue is just this map itself but I left the script running as I went to work today and came back to it being stuck in the pause menu. Running it now and the same issue happened again not sure if I've messed something up though!

**Comment by Valokoodari** [comment]
A video of this happening would be really helpful as I haven't been able to reproduce this at least for now. The script opening the pause menu is a known problem on harder modes when some monkey knowledge is missing but the deflation strategy on Dark Castle doesn't require any MK.

**Comment by Hush-ti** [comment]
Will try get a recording as I leave for work today 👍

**Comment by Hush-ti** [comment]
I believe I've fixed the issue. I didn't have beast handler unlocked so it was still running the esc key press leading itself into the pause menu

**Comment by Valokoodari** [comment]
That makes sense. Thank you.
