### ISSUE TITLE
Variable "GeneralEasy" never assigned a value

### ISSUE THREAD

**Issue by Qwas132** [Valokoodari/btd6-ahk#118]
main.apk doesn't work because maps --> beginner --> include contains variable GeneralEasy 
![image_2023-10-21_124046113]
![Screenshot 2023-10-21 124106](https://github.com/Valokoodari/btd6-ahk/assets/66559057/d772255a-b8f5-486b-8e03-cde8fed6cfca)
![Screenshot 2023-10-21 124231](https://github.com/Valokoodari/btd6-ahk/assets/66559057/ae9eba01-3765-4aec-b4f3-5fbb45817d6f)

**Comment by Qwas132** [comment]
Fixed the issue was using "visual studio code" to run the program instead dubble clicked on the script it self and it worked

**Comment by brickyosu** [comment]
> Fixed the issue was using "visual studio code" to run the program instead dubble clicked on the script it self and it worked

im still having the same issue even by running it with VSC

**Comment by brickyosu** [comment]
someone help :c
