### ISSUE TITLE
Issue launching

### ISSUE THREAD

**Issue by Isopod12** [Valokoodari/btd6-ahk#15]
![btd6](https://user-images.githubusercontent.com/92643916/137596046-1b58bc40-4c19-49b4-afea-a424bbcdfc21.JPG)
I am having some trouble launching the code, not sure if its the code or if I'm doing something wrong
(please help me, I would appreciate it)

**Comment by Isopod12** [comment]
![btd62](https://user-images.githubusercontent.com/92643916/137597016-1a21ca4a-a254-4dbe-ad38-a3af181da47c.JPG)
I think the folder was unzipped
Since it says it has trouble opening bloody, I tried to see what that error was, and this is the error that came up
Thank you for your response and help

**Comment by Valokoodari** [comment]
Unfortunately the scripts for the maps can't be used without the main script. But even then it shouldn't display an error when working properly and should just do nothing and exit.

Are you sure you're using AutoHotkey v2 and not v1? Sleep() being an nonexistent function points to the use of v1.
Issue #8 could help with using v2.

**Comment by Isopod12** [comment]
Thank you so much, that helped! 
Now the script selects the expert map with the bonus - however, it doesn't do anything when it loads in
(Im 99% sure its my fault, not the script, sorry)
Thank you for your help again
