### ISSUE TITLE
Dark Castle issue.

### ISSUE THREAD

**Issue by RavageMyRiven** [Valokoodari/btd6-ahk#16]
The script works fine, except for the fact that the resolution i think is fked on the placements on monkeys. Dart monkey is placed on the top left platform, and is never really placed because it hovers over the balloon path, as for the sub, it gets placed at the top right.
Sent two pictures on their locations, wanted to know if i can change it to fix it.

Also i opened up the "dark_easy.ahk" but it is written on what supposed to be 

Send("{vk51}")	;dart
			Sleep(timeScale * 100)
			MouseMove(547,477)
			Sleep(timeScale * 100)
			Click("547,477")
			Sleep(timeScale * 11200)
			
			Send("{vk55}")	;ben
			Sleep(timeScale * 100)
			MouseMove(1446,247)
			Sleep(timeScale * 100)
			Click("1446,247")
			Sleep(timeScale * 18700)
			
			Send("{vk41}")	;wizard
			Sleep(timeScale * 100)
			MouseMove(1001,443)
			Sleep(timeScale * 100)
			Click("1001,443")
			Sleep(timeScale * 100)
			
			Click("1001,443")	;click wizard
			Sleep(timeScale * 3600)

But it never selected the wizard, the first money that comes after benjamin is a sub. But on file it says its a wizard.

![Bug](https://user-images.githubusercontent.com/92662284/137613599-0c9c3df4-06a8-49cb-b01a-691e400ef84e.png)
![BUG2](https://user-images.githubusercontent.com/92662284/137613601-54f3d13c-66c7-4340-8259-95658fd73620.png)
t.

**Comment by Valokoodari** [comment]
The script seems to incorrectly detect Dark Castle as Bloody Puddles. I'll change the image used to detect Bloody Puddles to prevent this from happening.
