### ISSUE TITLE
bruh does this work with v1

### ISSUE THREAD

**Issue by GermanYoshi** [Valokoodari/btd6-ahk#2]
v2 is complicated to install

**Comment by Valokoodari** [comment]
The script does not work with AutoHotkey v1 as the syntax of v2 is quite different.
It is possible to convert the script to work with v1 but it's probably just easier to run it with v2.

1. Download the AutoHotkey v2 zip file and unpack it somewhere.
2. Right click the script
    > Open with
    > Choose another app
    > More apps
    > Look for another app on this PC
3. Navigate to where you unpacked the zip file and choose the AutoHotkeyU64.exe (or the AutoHotkeyU32.exe on a 32-bit os).

**Comment by GermanYoshi** [comment]
thanks and how do i activate the script if i tab in the game nothing happens

**Comment by Valokoodari** [comment]
The script is started with Ctrl+J and stopped with Ctrl+E.

**Comment by GermanYoshi** [comment]
it clicks 5 times on expert

**Comment by Valokoodari** [comment]
The newest version of the game seems to cause the image search to not work correctly and I'm not quite sure why.

But I made a temporary fix to circumvent that and it should now work after you download the newest version of the script.

**Comment by GermanYoshi** [comment]
bro your awsome :)
