### ISSUE TITLE
Infernal Fails round 10

### ISSUE THREAD

**Issue by ExpandDimmadome** [Valokoodari/btd6-ahk#22]
On round 10 in infernal, the game is lost. This seems to be because no towers are placed in the bottom half of the map, and so you leak every other round

**Comment by cam776** [comment]
there is supposed to be a monkey buckaneer but it fails to place it at also seams like it fails to place the monkey buckanear on all of the maps

**Comment by cam776** [comment]
Did more digging alot of the maps have timings that are off because of the new update

**Comment by cam776** [comment]
fixxed muddy:


muddyGameScript(timeScale) {
		if WinActive("BloonsTD6") {
			
			Sleep(timeScale * 100)	; clear hot key lag
			
			Send("{vk20}")		; Start game
			Sleep(timeScale * 100)
			Send("{vk20}")		; Increase Speed
			Sleep(timeScale * 100)
			
			Send("{vk51}")	;dart left
			Sleep(timeScale * 100)
			MouseMove(403,201)
			Sleep(timeScale * 100)
			Click("403,201")
			Sleep(timeScale * 7500)
			
			Send("{vk55}")	;ben
			Sleep(timeScale * 100)
			MouseMove(647,908)
			Sleep(timeScale * 100)
			Click("647,908")
			Sleep(timeScale * 10200)
			
			Send("{vk58}")	;sub
			Sleep(timeScale * 100)
			MouseMove(1195,470)
			Sleep(timeScale * 100)
			Click("1195,470")
			Sleep(timeScale * 100)
			
			Click("1195,470")	;click sub
			Sleep(timeScale * 5400)
			
			Send("{vkBC}")	;sub 100
			Sleep(timeScale * 7800)
			
			Send("{vkBC}")	;sub 200
			Sleep(timeScale * 6600)
			
			Send("{sc035}")	;sub 201
			Sleep(timeScale * 19000)
			
			Send("{sc035}")	;sub 202
			Sleep(timeScale * 30300)
			
			Send("{sc035}")	;sub 203
			Sleep(timeScale * 3300)
			
			Send("{vk51}")	;dart right
			Sleep(timeScale * 100)
			MouseMove(1108,185)
			Sleep(timeScale * 100)
			Click("1108,185")
			Sleep(timeScale * 100)
			
			Click("1108,185")	;click dart right
			Sleep(timeScale * 4900)
			
			Send("{sc035}")	;dart right 001
			Sleep(timeScale * 1500)
			
			Send("{sc035}")	;dart right 002
			Sleep(timeScale * 3100)
			
			Send("{vk5A}")	;sniper
			Sleep(timeScale * 100)
			MouseMove(1017,917)
			Sleep(timeScale * 100)
			Click("1017,917")
			Sleep(timeScale * 100)
			
			Click("1017,917")	;click sniper
			Sleep(timeScale * 100)
			
			Send("^{vk09}")	;change target priority to strong
			Sleep(timeScale * 6000)
			
			Send("{vkBC}")	;sniper 100
			Sleep(timeScale * 7200)
			
			Send("{sc035}")	;sniper 101
			Sleep(timeScale * 4700)
			
			Send("{sc035}")	;sniper 102
			Sleep(timeScale * 100)
			
			Click("960,540")	;click center of screen to dismiss menu
			Sleep(timeScale * 100)
			
			Click("403,201")	;click left dart
			Sleep(timeScale * 9200)
			
			Send("{sc035}")	;left dart 001
			Sleep(timeScale * 1700)
			
			Send("{sc035}")	;left dart 002
			Sleep(timeScale * 100)
			
			Click("1195,470")	;click sub
			Sleep(timeScale * 24000)
			
			Send("{sc035}")	;sub 204
			Sleep(timeScale * 100)
			
			Click("1017,917")
			Sleep(timeScale * 27300)
			
			Send("{sc035}")	;sniper 103
			Sleep(timeScale * 38200)
			
			Send("{sc035}")	;sniper 104
			Sleep(timeScale * 17500)
			
			Send("{vkBC}")	;sniper 204
			Sleep(timeScale * 100)
			
			Click("403,201")	;click left dart
			Sleep(timeScale * 5500)
			
			Send("{sc035}")	;left dart 003
			Sleep(timeScale * 1900)
			
			Send("{vkBE}")	;left dart 013
			Sleep(timeScale * 1700)
			
			Send("{vkBE}")	;left dart 023
			Sleep(timeScale * 10800)
			
			Send("{sc035}")	;left dart 024
			Sleep(timeScale * 100)
			
			Click("1108,185")	;click right dart
			Sleep(timeScale * 3600)
			
			Send("{sc035}")	;right dart 003
			Sleep(timeScale * 1600)
			
			Send("{vkBE}")	;right dart 013
			Sleep(timeScale * 1500)
			
			Send("{vkBE}")	;right dart 023
			Sleep(timeScale * 10400)
			
			Send("{sc035}")	;right dart 024
			Sleep(timeScale * 21400)	;wait for victory
		}
}

**Comment by cam776** [comment]
Fixed Ouch


ouchGameScript(timeScale) {
		if WinActive("BloonsTD6") {
		
			Sleep(timeScale * 100) ;clear hotkey lag
			
			Send("{vk20}")		; Start game
			Sleep(timeScale * 100)
			Send("{vk20}")		; Increase Speed
			Sleep(timeScale * 100)
			
			Send("{vk51}")	;dart
			Sleep(timeScale * 100)
			MouseMove(531,310)
			Sleep(timeScale * 100)
			Click("531,310")
			Sleep(timeScale * 10900)
			
			Send("{vk55}")	;ben
			Sleep(timeScale * 100)
			MouseMove(1273,251)
			Sleep(timeScale * 100)
			Click("1273,251")
			Sleep(timeScale * 10950)
			
			Send("{vk43}")	;boat
			Sleep(timeScale * 200)
			MouseMove(840,571)
			Sleep(timeScale * 200)
			Click("840,571")
			Sleep(timeScale * 200)
			
			Click("840,571")	;click boat
			Sleep(timeScale * 16000)
			
			Send("{vkBE}")	;boat 010
			Sleep(timeScale * 7500)
			
			Send("{vkBC}")	;boat 110
			Sleep(timeScale * 9900)
			
			Send("{vkBC}")	;boat 210
			Sleep(timeScale * 79900)
			
			Send("{vkBC}")	;boat 310
			Sleep(timeScale * 8500)
			
			Send("{vkBE}")	;boat 320
			Sleep(timeScale * 100)
			
			Click("531,310")	;click dart
			Sleep(timeScale * 4200)
			
			Send("{sc035}")	;dart 001
			Sleep(timeScale * 5900)
			
			Send("{sc035}")	;dart 002
			Sleep(timeScale * 12000)
			
			Send("{sc035}")	;dart 003
			Sleep(timeScale * 19200)
			
			Send("{sc035}")	;dart 004
			Sleep(timeScale * 2100)
			
			Send("{vkBE}")	;dart 014
			Sleep(timeScale * 2100)
			
			Send("{vkBE}")	;dart 024
			Sleep(timeScale * 4400)
			
			Send("{vk44}")	;ninja 1
			Sleep(timeScale * 100)
			MouseMove(995,187)
			Sleep(timeScale * 100)
			Click("995,187")
			Sleep(timeScale * 100)
			
			Click("995,187")	;click ninja 1
			Sleep(timeScale * 3600)
			
			Send("{vkBC}")	;ninja 1 100
			Sleep(timeScale * 1500)
			
			Send("{vkBC}")	;ninja 1 200
			Sleep(timeScale * 1900)
			
			Send("{sc035}")	;ninja 1 201
			Sleep(timeScale * 4700)
			
			Send("{vkBC}")	;ninja 1 301
			Sleep(timeScale * 28700)
			
			Send("{vkBC}")	;ninja 1 401
			Sleep(timeScale * 6900)
			
			Send("{vk44}")	;ninja 2
			Sleep(timeScale * 100)
			MouseMove(528,542)
			Sleep(timeScale * 100)
			Click("528,542")
			Sleep(timeScale * 100)
			
			Click("528,542")	;click ninja 2
			Sleep(timeScale * 3200)
			
			Send("{vkBC}")	;ninja 2 100
			Sleep(timeScale * 1900)
			
			Send("{sc035}")	;ninja 2 101
			Sleep(timeScale * 1700)
			
			Send("{vkBC}")	;ninja 2 201
			Sleep(timeScale * 1800)
			
			Send("{vkBC}")	;ninja 2 301
			Sleep(timeScale * 29300)
			
			Send("{vkBC}")	;ninja 2 401
			Sleep(timeScale * 62000)	;wait victory
		}
}

**Comment by cam776** [comment]
Fixed Ravien


ravineGameScript(timeScale) {
		if WinActive("BloonsTD6") {
			
			Sleep(timeScale * 100)	; Clear hot key lag
			
			Send("{vk20}")		; Start game
			Sleep(timeScale * 100)
			Send("{vk20}")		; Increase Speed
			Sleep(timeScale * 100)
			
			Send("{vk51}")		; Dart monkey
			Sleep(timeScale * 100)
			MouseMove(184,475)
			Sleep(timeScale * 100)
			Click("184,475")
			Sleep(timeScale * 13000)
			
			Send("{vk55}")		; Hero (Ben)
			Sleep(timeScale * 100)
			MouseMove(1208,399)
			Sleep(timeScale * 100)
			Click("1208,399")
			Sleep(timeScale * 35700)
			
			Send("{vk4A}")		; Spike Factory
			Sleep(timeScale * 100)
			MouseMove(711,814)
			Sleep(timeScale * 100)
			Click("711,814")
			Sleep(timeScale * 9300)
			
			Send("{vk56}")		; Plane 1
			Sleep(timeScale * 100)
			MouseMove(316,735)
			Sleep(timeScale * 100)
			Click("316,735")
			Sleep(timeScale * 100)
			
			Click("316,735")	; Click Plane 1
			Sleep(timeScale * 12000)
			
			Send("{sc035}")		; Plane 1 001
			Sleep(timeScale * 10300)
			
			Send("{sc035}")		; Plane 1 002
			Sleep(timeScale * 100)
			
			Send("^{vk09}")		; Change Target Priotity to Figure Eight
			Sleep(timeScale * 100)
			
			Send("^{vk09}")		; Change Target Priotity to Figure Infinite
			Sleep(timeScale * 59400)
			
			Send("{sc035}")		; Plane 1 003
			Sleep(timeScale * 10400)
			
			Send("{vkBC}")		; Plane 1 103
			Sleep(timeScale * 8700)
			
			Send("{vkBC}")		; Plane 1 203
			Sleep(timeScale * 11400)
			
			Send("{vk46}")		; Alch
			Sleep(timeScale * 100)
			MouseMove(207,848)
			Sleep(timeScale * 100)
			Click("207,848")
			Sleep(timeScale * 100)
			
			Click("207,848")	; Click Alch
			Sleep(timeScale * 4500)
			
			Send("{vkBC}")		; Alch 100
			Sleep(timeScale * 1500)
			
			Send("{vkBC}")		; Alch 200
			Sleep(timeScale * 12000)
			
			Send("{vkBC}")		; Alch 300
			Sleep(timeScale * 20700)
			
			Send("{vkBC}")		; Alch 400
			Sleep(timeScale * 7500)
			
			Send("{sc035}")		; Alch 401
			Sleep(timeScale * 10000)
			
			Send("{vk56}")		; Plane 2
			Sleep(timeScale * 100)
			MouseMove(453,835)
			Sleep(timeScale * 100)
			Click("453,835")
			Sleep(timeScale * 100)
			
			Click("453,835")	; Click Plane 2
			Sleep(timeScale * 4800)
			
			Send("{sc035}")		; Plane 2 001
			Sleep(timeScale * 1800)
			
			Send("{sc035}")		; Plane 2 002
			Sleep(timeScale * 14300)
			
			Send("{sc035}")		; Plane 2 003
			Sleep(timeScale * 4500)
			
			Send("{vkBC}")		; Plane 2 103
			Sleep(timeScale * 8200)
			
			Send("{vkBC}")		; Plane 2 203
			Sleep(timeScale * 10000)
			
			Click("711,814")	; Click Spike Factory
			Sleep(timeScale * 100)
			
			Send("{vkBE}")		; Spike 010
			Sleep(timeScale * 6400)
			
			Send("{vkBE}")		; Spike 020
			Sleep(timeScale * 6000)
			
			Send("{vkBC}")		; Spike 120
			Sleep(timeScale * 6500)
			
			Send("{vkBC}")		; Spike 220
			Sleep(timeScale * 4600)
			
			Send("{vk56}")		; Plane 3
			Sleep(timeScale * 100)
			MouseMove(330,923)
			Sleep(timeScale * 100)
			Click("330,923")
			Sleep(timeScale * 100)
			
			Click("330,923")	; Click Plane 3
			Sleep(timeScale * 3200)
			
			Send("{sc035}")		; Plane 3 001
			Sleep(timeScale * 1600)
			
			Send("{sc035}")		; Plane 3 002
			Sleep(timeScale * 18700)
			
			Send("{sc035}")		; Plane 3 003
			Sleep(timeScale * 2600)
			
			Send("{vkBC}")		; Plane 3 103
			Sleep(timeScale * 1900)
			
			Send("{vkBC}")		; Plane 3 203
			Sleep(timeScale * 11000)		; Wait for victory
		}
}

**Comment by cam776** [comment]
no problem working on other maps now
