### ISSUE TITLE
Quad fails round 28

### ISSUE THREAD

**Issue by ExpandDimmadome** [Valokoodari/btd6-ahk#23]
On round 28, quad loses everytime. The final upgrade is very quick throws to the dart monkey on round 15. Consistent leaks begin on round 19, and it seems the weak link is the upper right corner, where the base spike factory is located. 28 is simply where the whole thing falls apart, as a large portion of the map have no lead popping power

**Comment by Jezzkis** [comment]
Same here, Fail everytime on round 28

**Comment by Sungamriuz** [comment]
if you opend the folder you downloaded there should be  a file that says maps click that and right click on quad and add a few seconds on one of the sleep commands
