### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Porkyperson** [Valokoodari/btd6-ahk#25]
[](url
![AHK Error](https://user-images.githubusercontent.com/94727648/142711393-6a0dd3e6-1384-4e79-87a9-6553e4bf66a6.png)
how do I fix this? I'm very new to AHK
Also, Ctrl-Alt-Shift-J doesn't do anything

**Comment by jesramos** [comment]
https://github.com/Valokoodari/btd6-ahk/issues/2#issuecomment-827618511

**Comment by Porkyperson** [comment]
ok thank you. now ive done that, i open a script, press Ctrl-Alt-Shift-J and it presses play automatically, and then it stops
