### ISSUE TITLE
Cant play maps

### ISSUE THREAD

**Issue by drunksy** [Valokoodari/btd6-ahk#27]
I use this for the winter collection event. I changed the pictures in the res file to the new event symbols. Map selection works fine, but after selecting a map and going in game, it just stops. This is probably just for me the issue, but i dont know how to fix it

**Comment by Valokoodari** [comment]
Seems like the map is not being recognized as the map recognition is the first thing to happen after opening a map.

Not sure why it would fail though but it could be some of the following:
- Some weird processing of the graphics. (See [#13](https://github.com/Valokoodari/btd6-ahk/issues/13#issuecomment-945146810))
- Not running the game fullscreen with the resolution of 1920x1080.
- Something about graphics has changed in the newest update to the game.

**Comment by Valokoodari** [comment]
The recognition of some maps was affected by the cosmetic changes of the holiday collection event but that should be fixed now.
