### ISSUE TITLE
Stops after clicking Play at the title screen

### ISSUE THREAD

**Issue by Porkyperson** [Valokoodari/btd6-ahk#29]
When i press Ctrl Alt Shift J it clicks play on the menu screen to open up beginner maps. after that it stops doing anything. My curser is normal size and I have AHKv2. How do I fix it?

**Comment by nowheddos** [comment]
This is due to the project only supporting the Halloween event, it only knows how to search for the Halloween bonus images. (The little "Bonus Rewards" Icon on the maps)

**Comment by Porkyperson** [comment]
How do i replace with christmas

**Comment by Valokoodari** [comment]
The script should now work with the current collection event.
