### ISSUE TITLE
Setting up issues

### ISSUE THREAD

**Issue by Sungamriuz** [Valokoodari/btd6-ahk#31]
im having trouble using the script when i open it, there is an error on line 11 the program will exit

**Comment by jakcqc** [comment]
Make sure you are using autohotkeyv2

**Comment by Sungamriuz** [comment]
i downloaded it but it didnt do anything how do i run the script with ahk2

**Comment by Valokoodari** [comment]
There are screenshots in #8 to help with that.

**Comment by Sungamriuz** [comment]
maby im doing something wrong but i tried to open it witrh the 64bit thst i downloaded but i got the same error message

**Comment by Sungamriuz** [comment]
https://imgur.com/a/Zvl6ULx i opened with on the script end pressed the 64 bit

**Comment by Jezzkis** [comment]
put the AHK v2 file into the script folder, and drag collectionBot.ahk on top of AutoHotkey64.exe

**Comment by Sungamriuz** [comment]
Thank you it worked :D
