### ISSUE TITLE
Error At Line 11

### ISSUE THREAD

**Issue by MonkeySaint** [Valokoodari/btd6-ahk#33]
![image](https://user-images.githubusercontent.com/62266035/147216511-5d7646de-00ba-4e5d-9fec-a2790bbdde9a.png)
Dragging the .ahk file on the the exe in the same directory.

**Comment by Valokoodari** [comment]
If you drag the script on to the executable of AutoHotkey, you need to have the .exe in the same directory which the main script and the /maps directory are located in.

**Comment by MonkeySaint** [comment]
Yep that is how I have it. I also check the path that is the path to the maps folder.
