### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tszyau** [Valokoodari/btd6-ahk#37]
I tried the guides to download autohotkey v2 in previous dissucions but still failed,have no idea why
[https://imgur.com/a/4Ag9wN4](url)

**Comment by Valokoodari** [comment]
It seems like you're trying to use the AutoHotkey.chm (Compiled HTML Help) instead of the executables, The script should be run with either the AutoHotkey64.exe or the AutoHotkey32.exe.

**Comment by Tszyau** [comment]
thanks it worked. I'm bad to these type of computer stuff

**Comment by Tszyau** [comment]
wait after the script runs it keeps dying in sanctuary, seems like it cannot put down the spactory and if i put it down manually it will lose in r23 after placing a 100sniper and 000wizard

**Comment by Valokoodari** [comment]
You'll have to adjust the timeScale setting found on line 7 in the collectionBot.ahk. For example my secondary laptop requires it to be 1.20 instead of the default 1.00.

**Comment by Tszyau** [comment]
Thanks now the script is running perfectly
