### ISSUE TITLE
Script Won't Wun

### ISSUE THREAD

**Issue by ItWasYou** [Valokoodari/btd6-ahk#42]
I'm new to AHK, and I'm having trouble running the script. If I try to run the collectionBot.ahk file, it says "Error at line 11. Maps\bloody_easy.ahk cannot be opened. The program will exit." When trying to run bloody_easy it says "Error: Call to nonexistant function. Specifically: Sleep(timeScale * 100). The program will exit."
I assume that I am doing something wrong on my end, due to being a complete novice, so help would be appreciated.

**Comment by machasins** [comment]
You need to run it with AHK v2. You can download it [here](https://www.autohotkey.com/download/ahk-v2.zip). There is also a download link on the readme.

**Comment by ItWasYou** [comment]
Managed to get it working after a few tries, but noticed that it never tries to enter the second page of the expert maps unless the mouse is moved. Is there a way to fix this?

**Comment by machasins** [comment]
Try changing your cursor size to the smallest option. If you use a large cursor, it can block the script from finding the expert button.

**Comment by TijnL64** [comment]
> Managed to get it working after a few tries, but noticed that it never tries to enter the second page of the expert maps unless the mouse is moved. Is there a way to fix this?

i have this issue aswell. when i drag the collectionBot.ahk into the v2 it gives me that error how did you fix it?

**Comment by ItWasYou** [comment]
I fixed the opening error by right clicking the script, selecting 'Open With', clicking more apps, and then selecting the 64bit version, which worked perfectly.

**Comment by TijnL64** [comment]
but if i do that it gives the error messege you gave before. do you select it from the file you downloded?

**Comment by TijnL64** [comment]
> but if i do that it gives the error messege you gave before. do you select it from the file you downloded?

got it to work but when i open bloons and try to activte it nothing happends

**Comment by Valokoodari** [comment]
Closing this issue as there is now an [installer](https://www.autohotkey.com/download/ahk-v2.exe) for AutoHotkey v2 which should be easier to use than the manual method from beta versions.
