### ISSUE TITLE
opens map menu then dies

### ISSUE THREAD

**Issue by oRevex** [Valokoodari/btd6-ahk#43]
just stops idfk

**Comment by machasins** [comment]
Try changing your cursor size to the smallest setting. If the cursor is large, it can block the script from recognizing icons on the screen. 

In this case, I think the script is having trouble finding the expert button when the cursor is already on it. Hope this helps.

**Comment by oRevex** [comment]
> Try changing your cursor size to the smallest setting. If the cursor is large, it can block the script from recognizing icons on the screen.
> 
> In this case, I think the script is having trouble finding the expert button when the cursor is already on it. Hope this helps.

Doesn't help

**Comment by Valokoodari** [comment]
Either the `res/stage_select.png` or `res/expert.png` is not matched by AutoHotkeys ImageSearch for some reason.

The best solution in this case would probably be to replace those two images.
