### ISSUE TITLE
[enhancement] Overwrite saves

### ISSUE THREAD

**Issue by gnomechewer** [Valokoodari/btd6-ahk#47]
When the script attempts to play a map that already has a save file on it, the script stops functioning. This can be fixed by adding another function called by "switch menuState" for the overwriting saves prompt. Here is a link to an image of the "Overwrite Save" prompt: https://imgur.com/a/psUjbnL

**Comment by Valokoodari** [comment]
It's finally possible to allow overwriting saves by setting `overwriteSave=true` in the `config.ini`.
