### ISSUE TITLE
Opens maps, wont play them

### ISSUE THREAD

**Issue by peekopeeko** [Valokoodari/btd6-ahk#48]
I run the script and it opens the right map just fine, but it won't do anything past that. I tried messing around with the script speed to see if it was a lag issue but nothing changed.

**Comment by Valokoodari** [comment]
Most likely a problem with the map recognition or could also be that the script doesn't recognize to even be in a map.

Replacing `res/in_game.png` or the recognition image(s) for the problematic map(s) in `res/maps` should solve the problem.
