### ISSUE TITLE
No support for Firework Collectionevent

### ISSUE THREAD

**Issue by LenniGer** [Valokoodari/btd6-ahk#50]
The program doesn't work with the new Firework Collection Event! Is there a fix to that?

**Comment by denialp1** [comment]
replace the pngs in the res/totem_collection/ folder with new snippets of the firework logo

**Comment by LenniGer** [comment]
I tried that but the script only switches between the map pages. Is there anything I need to look out for when making the snippets?

**Comment by denialp1** [comment]
Yea I had to make sure snippets didn’t include much of the border bc sometimes the background of the map would show up, bit tedious and ended up changing most of them individually at the end.

**Comment by denialp1** [comment]
Yea this was tripping me up bc to my understanding the script loops through each expert map png from the folder (on one page, then swap to next if not found) and attempts to click for each map. Therefore I’m thinking that you have to have the bonus logo on the specific map and snip them for every map which seems way to tedious, so I’m not sure (I haven’t gotten mine fully working yet). Worst case might have to run through each of the maps once to get the png and then good to go, or more likely there’s a much easier fix that I’m missing.

**Comment by denialp1** [comment]
Nvm I’m tripping I think it should work if it’s just the same png snipped small enough so there’s no background, bc there’s only one fireworks badge on the screen at a time

**Comment by Valokoodari** [comment]
There is now support for the firework collection event.

And I also finally updated the script to only require six different images for the map selection.
