### ISSUE TITLE
Looping Issue With No Result

### ISSUE THREAD

**Issue by OrangePieTaster** [Valokoodari/btd6-ahk#51]
When launching the program, nothing occurs. Going into the code, with some knowledge, i changed the bindings to control+q and w for start and stop. Nothing happened still. After adding a simple mouse move function, it was looping through lines 30-47, I assume trying to find the correct match maybe? Maybe the image is wrong?
Resolution is set correctly for sure.

**Comment by AfroBob** [comment]
Do you happen to have set the mouse cursor to (X)L?

It got stuck in the menu for me of the event map was on the 2nd page of the expert maps, setting the cursor to default size fixed that for me.

**Comment by OrangePieTaster** [comment]
That makes sense, but after setting it it to both Large and Normal, it still does not move forward after starting

**Comment by Valokoodari** [comment]
The simplest solution would likely be to replace `res/play_home.png` and/or `res/stage_select.png`.

**Comment by Valokoodari** [comment]
Closing as #49 is at least mostly the same issue.
