### ISSUE TITLE
Monkeys Can't Be Placed (Works On Some Maps Broken On Others)

### ISSUE THREAD

**Issue by MrRyno123** [Valokoodari/btd6-ahk#52]
It tries to put monkeys in places where they can't be placed. So far this has happened on sanctuary and ravine but I haven't tried all of the maps yet so it could be more.

**Comment by AfroBob** [comment]
The problem seems to be with Ravine, the image to identify the map was the issue for me. There are fireworks in the current event that aren't in the picture.

I replaced it with a picture with a part of the bridge and that fixed it for me.

**Comment by MrRyno123** [comment]
Yep, that did it. Thanks

**Comment by MrRyno123** [comment]
For some reason now its using the ravine script on every map. I tried retaking the snips but it doesn't change anything.

**Comment by AfroBob** [comment]
Maybe your new image is to "general", this is my new snap for ravine:
![ravine](https://user-images.githubusercontent.com/34006615/177212130-324e261c-0f1f-44c0-9b97-948701528f51.png)

**Comment by MrRyno123** [comment]
Ok that seems to work. Hopefully it’ll work for all the maps this time

**Comment by FlamingNinja42** [comment]
I'm also having some issues with ravine, even with a different image (the one from AfroBob), it occurs to me that quite a bit of the confetti from the July event seems to cross that section of the map, maybe that's also causing this issue.

**Comment by kwalk123** [comment]
A more reliable way to do this for maps would be a separate search image function with coordinates -- assuming there are coordinates on every map that do not have animation. This would be a faster search without having to scan the full screen, more reliable, and would enable looping until the map is found to handle confetti, falling leaves, etc.

**Comment by Valokoodari** [comment]
### Todo
- [ ] Optimized map recognition

**Comment by Valokoodari** [comment]
The map recognition has now been updated.
