### ISSUE TITLE
it just stops after the game end screen

### ISSUE THREAD

**Issue by Vortecked** [Valokoodari/btd6-ahk#6]
i looked in resources, theres an image for the next button, so i would assume there is a part of the script that searches for that button and clicks on it when the game is done, however, it just stays on the game end screen that says victory

**Comment by Valokoodari** [comment]
The current version shouldn't read the screen at any point.

There could be quite a long delay (maybe up to 30 seconds) after the game finishes before the script does anything as sometimes the game runs a bit slower and sometimes a bit faster. So are you sure that the script stops and it's not just the time buffer at the end?

**Comment by Vortecked** [comment]
ohhhh never mind, i did not realize that i just had to wait a minute. after a minute, it pressed next and did it again
