### ISSUE TITLE
Sanctuary map not working

### ISSUE THREAD

**Issue by Vampy26** [Valokoodari/btd6-ahk#60]
Hi all, 

Having a bit of an issue with the script, recently started using it and it works fine for most maps now, I have to change the timescale from 1.00 to 1.20 to get it to work on workshop/puddles maps however on sanctuary even with the timescale change it gets stuck on the same part around half way when the script goes to buy the wizard monkey it tries placing it on a moving block which moves before it places and the script just ends up holding the wizard till defeat, any ideas how to fix this, I have been reading the other threads and they state to update the res file however I am not sure what image I am supposed to be updating the file with, is it just a small image from anywhere on the map or a specific area? 

Any help on this at all whilst the totem event is live?

**Comment by Valokoodari** [comment]
I'd recommend trying smaller values (like 1.05, 1.10 and 1.15) for the time scale as it seems like 1.20 could be too slow. At least the first wizard should be placed way before the platform moves away from the corner.

No need to update any of the images when everything seem to be recognized properly.

Hopefully you find the correct value for the time scale on Sanctuary as it unfortunately requires the timings to be almost perfect.

**Comment by MrHouck** [comment]
I don't get the whole point of this script if it's supposed to be AFKable, why do we always have to change the timescale then? doesn't sound super AFK to me

**Comment by Valokoodari** [comment]
You just need to find the correct time scale value once as for some reason either the game or AutoHotkey (I have not timed it to see which one it actually is) runs at different speeds on different machines.

I have managed to have the script running for a week straight before the game crashed and I had to restart it.

**Comment by Wormie7** [comment]
I don't think it's letting me actually change the time scale. I noticed the change in time scale setup where on line 14 it says:

global timeScale := IniRead("config.ini", "settings", "timeScale", 1.00)

I try changing the 1.00 to 1.20 and there doesn't seem to be a difference when I try running the script. To double check, I tried running the script at 2.00 time scale and nothing changes. Every time on Sanctuary, Benjamin is placed just a little too early before the beginning of round 2. Do you know why this is happening?

**Comment by Vampy26** [comment]
I've tried changing time scale too and not sure if it does make too much difference 1.05 10 and 15 all failed on Santuary, it does all the other placements each time its around round 14 and then it tries to place the wizard and fails - so strange. What I did want to ask is can I edit the maps that rely so hard on placement timing to just use non moving areas like the top middle in sanctuary, I've been able to complete with just snipers/spike factories for example, might be good for future versions of the map.

**Comment by Valokoodari** [comment]
All of the game script now read the round number and the `timeScale` has been permanently removed.
