### ISSUE TITLE
Sanctuary

### ISSUE THREAD

**Issue by DarkPie187** [Valokoodari/btd6-ahk#65]
It places a glue gunner instead of a sniper and the wizard tries to get placed too early which means it doesnt place when the platform moves

**Comment by DarkPie187** [comment]
> It places a glue gunner instead of a sniper and the wizard tries to get placed too early which means it doesnt place when the platform moves

I just realised it places the gluegunner instead of a sniper on other maps too, i got the 1920 resolution and all hotkeys set to default language on english aswell.

**Comment by Valokoodari** [comment]
There was a similar issue (#62) to this caused by a qwertz keyboard layout instead of qwerty.

The simplest solution to this problem would be to swap y and z in game settings but you could also edit the script to press z instead of y.
