### ISSUE TITLE
collectionbot work but other dosen't

### ISSUE THREAD

**Issue by szefgg** [Valokoodari/btd6-ahk#68]
I cant even run any of script, but only collection bot works

**Comment by Valokoodari** [comment]
The map scripts are not intended to be used separately but it's possible to edit them to work without the main script:

```
#Include "%A_ScriptDir%\utils.ahk"

...GameScript() {
    ...
}

<hotkey>:: {
    ...GameScript()
}
```

Note that the edited map script will not work with the main script. You also must have the `utils.ahk` (and the `config.ini` to change the timeScale) in the same directory as the edited map script.
