### ISSUE TITLE
v34.3 Script doesn't start, ImageSearch Error

### ISSUE THREAD

**Issue by ugsusu** [Valokoodari/btd6-ahk#69]
The script seems to try loading something from a /none/ directory, that doesn't exist within the files. 

![image](https://user-images.githubusercontent.com/123708073/218258019-15399ed5-c545-4900-838d-91a07dfebf93.png)

**Comment by Valokoodari** [comment]
This should now be fixed on the main branch.

**Comment by ugsusu** [comment]
Error doesn't appear anymore (thanks!!), however the script doesn't seem to start - nothing happens after pressing the hotkey.

**Comment by Valokoodari** [comment]
Seems like ImageSearch cannot recognize the game state for some reason. Please check that everything is set according to the requirements listed in the [README](/Valokoodari/btd6-ahk/blob/main/README.md#requirements). If the script still doesn't work, you should check the log file (logging is only enabled by default after the commit [afb4022](https://github.com/Valokoodari/btd6-ahk/commit/afb4022209d20ebe8ccb0047748844ead847d75d)) and probably change some of the files (`play_home.png`, `stage_select.png`, `in_game.png`) in the `res` folder.

Also changing some settings in the graphics control panel could help: https://github.com/Valokoodari/btd6-ahk/issues/13#issuecomment-945146810

**Comment by ugsusu** [comment]
Replacing the images fixed it! Thanks a lot
