### ISSUE TITLE
pretty urgent issue

### ISSUE THREAD

**Issue by Vortecked** [Valokoodari/btd6-ahk#7]
it drains all my monkey money if it ends up losing cuz it spends all the money on continues for some reason. i had 30k and left it overnight and came back to 5k and it had half a million cash in game, since it kept buying continues

**Comment by Valokoodari** [comment]
That should definitely never happen and I'm really sorry for that. :/

I made a hotfix to prevent this from happening but it's not a perfect fix.

I will try to fix the screen reading in July to automatically detect a defeat and to recover from it.
