### ISSUE TITLE
Menu state not recognized

### ISSUE THREAD

**Issue by pireneus** [Valokoodari/btd6-ahk#75]
so this happens when i start the macro
https://www.dropbox.com/s/8cucxp3e5g3buuy/Bloons%20TD%206%202023.02.27%20-%2015.44.55.21.DVR_Trim.mp4?dl=0

these are the logs
![notepad_fFK3fCAbXI](https://user-images.githubusercontent.com/5862713/221595555-47a4a3b8-06e5-4129-8c8a-f9e91fd25401.png)

**Comment by pireneus** [comment]
yesterday i left it over night and it worked fine after 8 hours or so it stopped on one of the maps victory screen.
after that this happens every time

**Comment by Valokoodari** [comment]
I have no idea why it would suddenly stop working like that but I suggest replacing the image `img/states/in_game.png` with a similar one cropped from a screenshot taken on your machine.

**Comment by pireneus** [comment]
This seem to have fixed it thank you.
And i might know why 
![BloonsTD6_cm3H6eCSDZ](https://user-images.githubusercontent.com/5862713/221667265-ad38eabd-ea0d-412f-92df-377f972690a0.png)
you see i have the gforce experience icons down in the right corner and they might overlapped,i cropped the image to not contain these and now it is working
