### ISSUE TITLE
Wont detect game

### ISSUE THREAD

**Issue by G1Apples** [Valokoodari/btd6-ahk#80]
LogMsg("Script stopped because the game windows wasn't active") 
The game is running in told settings, config data is set to totem but it wont find the game.
am i just stupid or is there something wrong ?

**Comment by Valokoodari** [comment]
Try clicking on the game so that it's the active window before starting the script.

**Comment by G1Apples** [comment]
Now im sitting here with "Menu state not recognized" like in #75 
changing img/states/in_game.png with an cropped screenshot didnt work for me.

**Comment by Valokoodari** [comment]
Does this happen in all possible states (main menu, level selection, in game)? Could you attach a screenshot of the game from when this happens?

**Comment by Kerruya** [comment]
I am having the exact same thing
My script keeps switching maps ( swiping the screen from left, right, left, right)  But it doesn't click on the map. He doesn't select the map. 
Also, when I choose the map for the bot, and I start the script after. then after the script finishes the map, it doesn't continue. It stays stuck at victory.

**Comment by Kerruya** [comment]
![image](https://user-images.githubusercontent.com/129910799/229945682-d1d93869-630d-4223-826e-47f0dd4fdbee.png)

**Comment by Kerruya** [comment]
![image](https://user-images.githubusercontent.com/129910799/229945772-97659c4f-36f3-4803-b4c1-69d4891b26e6.png)
It doesn't go further than this.

**Comment by Valokoodari** [comment]
> –– script keeps switching maps ( swiping the screen from left, right, left, right) But it doesn't click on the map. ––

> –– after the script finishes the map, it doesn't continue. It stays stuck at victory.

Both of these problems should now be fixed.
