### ISSUE TITLE
Maps not being recongnized

### ISSUE THREAD

**Issue by Herschey2** [Valokoodari/btd6-ahk#84]
For most maps I have not gone through all of them it just spams this: 
[14:48:18] Script started
[14:48:18] in_game
[14:48:18] Map not recognized

**Comment by minindy** [comment]
I think its because of the easter events adding new things on the map. I have taken new screenshots which are working for the easter event but idk if they will work once the easter map decorations go away...

**Comment by Herschey2** [comment]
> I think its because of the easter events adding new things on the map. I have taken new screenshots which are working for the easter event but idk if they will work once the easter map decorations go away...

Where did you take the pics on the map because i tried taking new pics and it did not work

**Comment by masonLovett** [comment]
I just used windows snipping tool and picked a spot on the map without easter decorations. Then save it in img/maps, reload the script and see if it works. I had to do this for Muddy Puddles and Dark Castle so far but it has worked.

**Comment by Valokoodari** [comment]
Map selection has now been completely rewritten and map recognition isn't a thing anymore.
