### ISSUE TITLE
Error: Error: Script file "C:\Users\hanne\Desktop\btd6-ahk-main" cannot be opened.

### ISSUE THREAD

**Issue by NijaCake545** [Valokoodari/btd6-ahk#86]
i unzip the file but this is happening 

![Screenshot 2023-04-06 225303](https://user-images.githubusercontent.com/130080132/230491788-ce51f024-8240-44d5-a1d4-a6e26802a20f.png)

**Comment by NijaCake545** [comment]
(when I try to start the script)

**Comment by NijaCake545** [comment]
I right click on the main script and then run it using AutoHotke 2.0 64-bit
but when i press Ctrl + Alt+ Shift+j nothing happens.

Is there a way to run the Entire folders.

Thanks for the help

Valokoodari ***@***.***> schrieb am Di., 11. Apr. 2023, 12:16:

**Comment by m00rex** [comment]
The path shown in the screenshot is \Desktop\btd6-ahk-main, but main is the script inside the folder btd6-ahk, so the path should be \Desktop\btd6-ahk\main
But I dont know how AutoHotKey would get the path wrong if you opened the script directly via the explorer
