### ISSUE TITLE
"Menu State not recognized"

### ISSUE THREAD

**Issue by LaggyGlitch0779** [Valokoodari/btd6-ahk#91]
Log says menu state not recognized after beating a map, even though its been successsful on the same maps multiple times
logs here
[log.txt](https://github.com/Valokoodari/btd6-ahk/files/11206675/log.txt)

**Comment by TheFallenLeo** [comment]
Also having this issue. 
[log.txt](https://github.com/Valokoodari/btd6-ahk/files/11217536/log.txt)

**Comment by TheFallenLeo** [comment]
Any updates? Ruins afking while sleeping or working if I dont have access to computer. It just happens randomly when running the script, and will just get stuck on the victory menu.

**Comment by Valokoodari** [comment]
This should now be fixed by 0d8057f495fd8b03a162af3d2ced1ae42d330bae and c0a056ec643331bfc91963911d84a4d2041298a9.
