### ISSUE TITLE
Macro randomly opening file directory

### ISSUE THREAD

**Issue by LaggyGlitch0779** [Valokoodari/btd6-ahk#92]
I have a bot that screenshots my pc screen every few minutes so i can check in on the macro.  This morning I checked the screenshots, 
![B3C0A37B-B1A7-4DF1-9E61-705162AA4816](https://user-images.githubusercontent.com/74420805/231537892-9dca9481-cbea-4ee5-b68d-177f73b33f7a.jpeg)
 The macro’s file directory was open, even though i had not touched the game since the day before. idk if this is a bug or if im doing something wrong.

**Comment by Valokoodari** [comment]
I don't think there's any way the script alone could have done that.

**Comment by Valokoodari** [comment]
I have managed to replicate this and it seems to be a problem with Windows.
