### ISSUE TITLE
Script stoping after completing new map

### ISSUE THREAD

**Issue by Luuqas** [Valokoodari/btd6-ahk#95]
The script works perfectly fine until it clears "dark dungeons", then it stops and won't continue replaying maps.

**Comment by Valokoodari** [comment]
Please at least include the log (from `logs/log.txt`) and tell which screen it gets stuck on.

**Comment by Luuqas** [comment]
My bad, i did some testing and turning off hints made all work as intended. My apologies.

**Comment by Valokoodari** [comment]
Thank you for this information. Turning hints off has now been added to the requirements list.
