### ISSUE TITLE
Issue with Qwertz Keyboard Layout

### ISSUE THREAD

**Issue by m00rex** [Valokoodari/btd6-ahk#96]
I tried the script and kept losing because the script bought a glue gunner instead of a sniper. This happened because the game register the "Z" on QWERTZ Layout as a "Y" which is the hotkey for the glue gunner.
Changing the Sniper Keybind to Y resolved the issue

**Comment by Valokoodari** [comment]
The keys used by the script can now be changed in the file `data/keys.ahk`.
