### ISSUE TITLE
Script breaks after going into map selection menu

### ISSUE THREAD

**Issue by thatmanwhousesgithub** [Valokoodari/btd6-ahk#97]
After starting, the script enters the map selection menu, then bugs out saying "Menu state not recognized"
![Screenshot 2023-04-24 194706](https://user-images.githubusercontent.com/116285356/234154478-28d768eb-8558-4199-b2e6-a3a17e0474e7.png)

**Comment by GreamDesu** [comment]
Same issue, log file states:
[05:21:36] Script started
[05:21:37] Menu state not recognized

Resolution is correct, game running on the second fulhd monitor

**Comment by Valokoodari** [comment]
> Resolution is correct, game running on the second fulhd monitor

Have you tried running the game on the other display? AutoHotkey's default coordinate system has universal coordinates across displays.

**Comment by thatmanwhousesgithub** [comment]
Sorry for being 2 months late
![image](https://github.com/Valokoodari/btd6-ahk/assets/116285356/80fbc242-de4b-44ee-ad4c-48e6839cddd4)
I don't know what to do
Next ill try to replace ingame.png with my own image but first I need you to tell me what ingame.png even is

**Comment by Valokoodari** [comment]
As the problem happens in map selection, you could replace the `img/states/map_selection.png`.

![image](https://github.com/Valokoodari/btd6-ahk/assets/28293838/84ab3633-d405-47e7-9c32-583fdefe39ee)

But since you asked for `in_game.png` and it could have the same problem:

![image](https://github.com/Valokoodari/btd6-ahk/assets/28293838/419b3d25-75e5-42af-bba6-f4b743e88b87)

**Comment by Valokoodari** [comment]
I'd guess you have additional anti-aliasing or something like that enabled in your graphics control panel as that has caused problems like this before. You probably have to replace most of the images which takes some work or figure out which additional graphics settings are enabled and disable them to have the existing images work.

**Comment by thatmanwhousesgithub** [comment]
Thank you so much, I had AMD adrenalin software for my GPU and image sharpening was on, turning it off had fixed it!
