### ISSUE TITLE
doesnt upgrade monkeys

### ISSUE THREAD

**Issue by notnotcz** [Valokoodari/btd6-ahk#99]
i have all upgrades needed but when it tries to upgrade monkeys nothing hapens it just clicks on the monkey

**Comment by Valokoodari** [comment]
Do you have the default hotkey settings in the game? And which keyboard layout do you have?

**Comment by notnotcz** [comment]
i didnt change any hotkeys and im using czech layout

**Comment by Valokoodari** [comment]
By what I can find, that layout shouldn't cause any problems as the three keys next to the right shift are <kbd>,</kbd>, <kbd>.</kbd>, and <kbd>-</kbd> which are the same as in the Finnish layout. You could use AutoHotkey's [InstallKeybdHook](https://www.autohotkey.com/docs/v2/lib/InstallKeybdHook.htm) to check the keycodes (vk__ and sc___) for those keys in case they are different for some reason.

**Comment by Valokoodari** [comment]
The keys used by the script can now be changed in the file `data/keys.ahk`.
